language: php
php:
  - '5.3'
  - '5.6'
  - '7.0'
before_script:
  - curl -sL https://deb.nodesource.com/setup | sudo bash -
  - sudo apt-get update
  - sudo apt-get install -y nodejs
  - npm install -g gulp
  - npm install
